Script started on 2019-04-23 19:06:34+08:00 [TERM="xterm" TTY="/dev/pty0" COLUMNS="80" LINES="24"]
]0;~
[32m煜庭@DESKTOP-9T8HL2H [33m~[0m
$ g++ l[K-o lab1 lab.[K1.cpp
]0;~
[32m煜庭@DESKTOP-9T8HL2H [33m~[0m
$ ./lab1.exe
Please insert a number:22
sh: pause：命令找不到
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 ]0;~
[32m煜庭@DESKTOP-9T8HL2H [33m~[0m
$ exit

Script done on 2019-04-23 19:07:33+08:00 [COMMAND_EXIT_CODE="0"]
